// Dumps the ingested catalogue to a JSON file so the data lives in the
// repository rather than only in someone's local database.
//
// The ingestion runs on a machine with network access (a CI runner, say);
// this makes its result portable, reviewable in a diff, and re-seedable
// anywhere without crawling again.
//
//   npm run catalog:export

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { PrismaClient } from "../src/generated/prisma/client.ts";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT = path.join(ROOT, "prisma", "seed-data", "catalog.json");

const url = process.env.DATABASE_URL;
if (!url) throw new Error("DATABASE_URL is not set.");

const db = new PrismaClient({ adapter: new PrismaBetterSqlite3({ url }) });

try {
  const books = await db.book.findMany({
    orderBy: { title: "asc" },
    include: { chapters: { orderBy: { index: "asc" } } },
  });

  const payload = {
    _note:
      "Generated by scripts/export-catalog.mjs from an ingestion run. Edit the " +
      "crawler, not this file.",
    exportedAt: new Date().toISOString(),
    books: books.map((book) => ({
      slug: book.slug,
      title: book.title,
      author: book.author,
      narrator: book.narrator,
      coverUrl: book.coverUrl,
      description: book.description,
      category: book.category,
      language: book.language,
      sourceUrl: book.sourceUrl,
      license: book.license,
      chapters: book.chapters.map((chapter) => ({
        title: chapter.title,
        audioUrl: chapter.audioUrl,
        duration: chapter.duration,
      })),
    })),
  };

  await mkdir(path.dirname(OUT), { recursive: true });
  await writeFile(OUT, JSON.stringify(payload, null, 2) + "\n");

  const chapters = payload.books.reduce((sum, b) => sum + b.chapters.length, 0);
  const size = (JSON.stringify(payload).length / 1024 / 1024).toFixed(2);
  console.log(`Exported ${payload.books.length} books / ${chapters} chapters (${size} MB)`);
  console.log(`-> ${path.relative(ROOT, OUT)}`);
} finally {
  await db.$disconnect();
}
